### PR TITLE
Get user scope

### PR DESCRIPTION
**Pull request by L1qu1d1c3**
This feature allows you to set what information you want to request from the user when signing in. I've updated the "setup.md" file explaining this functionality and its limitations - seen as it's currently in Beta, Apple does not provide this user information just yet, but you can configure your app to request it so when it's finally released/allowed, your app already has the necessary permissions to gather this information.

### CODE REVIEW

**Comment by nicokaiser** [comment]
Where did you get the information how scopes and getting user information (`name`, `email`) may work? I did not find anything about that in the Apple docs...

**Comment by ananay** [comment]
@L1qu1d1c3, sorry for the delay in merging the request. I will test the code on my end before merging. @nicokaiser I think this is in the OpenID scope spec.

**Comment by nicokaiser** [comment]
By the way, the `email` scope is already provided by apple (it is an additional property if the `id_token`. Don't know how `name` will be submitted, probably as an objekt with firstname and lastname, but we don't know for sure yet.

**Comment by ajcase** [comment]
I also made this code change as well but saw it was already submitted for a pull. Can we merge this? Here is more documentation from Apple: https://developer.apple.com/documentation/signinwithapplejs/clientconfigi/3230955-scope

**Comment by L1qu1d1c3** [comment]
Until Apple decides to finally release this feature, we won't know what properties will be provided.
This PR is mainly for getting ahead of ourselves and asking the users to give us that information when it eventually becomes available. This avoids us having to invalidate them on our end or the users having to unauthorize the application on their end.

**Comment by nicokaiser** [comment]
Actually this feature is released already. However, the `name` property is not submitted alongside the `email` property in the ID Token, but rather in the POST with the `code` (and only if `response_mode=form_post` is used). 

This is a working implementation for Passport.js: https://github.com/nicokaiser/passport-apple

**Comment by ananay** [comment]
I've merged this PR, but there are some more changes required that I'll do myself.
- Add ```id_token``` in ```response_type```
- Add ```response_type=form_data```

**Comment by ananay** [comment]
Okay, so I've added the stuff mentioned above and updated the repository. However, I still don't get an email address in my response despite requesting the name and the email scopes!

Here's the running example with the problem: https://apple.ananay.dev

@nicokaiser could you please help me how to fix this issue? Thanks!

**Comment by nicokaiser** [comment]
If you change the response_mode to form_post, you need to retrieve the `code` with `req.body.code` (and probably use something like [body-parser](https://github.com/expressjs/body-parser)).

You then get `req.body.code`, `req.body.user` (which is a JSON with `{ name: { firstName, lastName }`). The ID Token contains the `email` property, if you configure the scope like `name email`.

I can try to adjust this repository and apple-auth-example to work in the next days, or you can have a look at [nicokaiser/passport-apple](https://github.com/nicokaiser/passport-apple), which does all this ;-)

**Comment by ananay** [comment]
Great work on the passport library @nicokaiser!
I've already added response_mode = form_post but all I get is this:

```
{ state: '91626fe4d9',
  code: 'c0bed5bed044e4812ae908e4b39fc52c6.0.ntrs.8GubVEEn-o0BPf78MrIl_Q',
  id_token: 'eyJraWQiOiJBSURPUEsxIiwiYWxnIjoiUlMyNTYifQ.eyJpc3MiOiJodHRwczovL2FwcGxlaWQuYXBwbGUuY29tIiwiYXVkIjoiY29tLmFuYW5heWFyb3JhLmFwcGxlYXV0aGV4YW1wbGUiLCJleHAiOjE1NjY1MDIwMDIsImlhdCI6MTU2NjUwMTQwMiwic3ViIjoiMDAwMzEyLmZlNTNkMzhjYWMyNzQ5NjQ5YTMxMWJlNTZlYTQ5NWY3LjIzMzIiLCJjX2hhc2giOiJMMzEyNDRZRHl1Mk9BQ1ZNYlY0SE9BIiwiYXV0aF90aW1lIjoxNTY2NTAxNDAyfQ.lKE_kMSkw7Lg_3QqfjYO9uekSKRtUQfHK1oeu9erG9SIjc3Z7PpeyGBhcCjUOBFOxDGgdkL-xloWSs1Y8cH8_rga19ruOiuDiusnaHlTlkdwVvLtbA6Qp7dPUQszZRT9Cyh5Dk3l8WasosMSNEuHeGv_WI1JaKJuFJy3-QjGHSUzXH24uvvMAniL-YHlHwoNdWcWv14g7nup0BZNIUsrU-sR1IMhOy2Pc7h-tcgOPd8O_gitrP-18R3mtlRuSxAWuHqHCCzolvKSZLE9UalEN1Ep6blrLVOtMrib0Kjvy3NnkILMfr-ZhQoDkX3MddmKdFEcpoCRttWxau8Emxx8MQ' }
```

**Comment by nicokaiser** [comment]
I added a PR to apple-auth-example with makes it work with all the user data. However this library has some shortcomings:

- The `state` that is returned from Apple needs to be checked if it is the same that you sent (you might need to use sessions for this)
- The `client_secret` (generated JWT) can have a much shorter TTL than 6 months. Maybe some minutes (as it is generated on every request anyway).

**Comment by nicokaiser** [comment]
> Great work on the passport library @nicokaiser!
> I've already added response_mode = form_post but all I get is this:
> 
> ```
> { state: '91626fe4d9',
>   code: 'c0bed5bed044e4812ae908e4b39fc52c6.0.ntrs.8GubVEEn-o0BPf78MrIl_Q',
>   id_token: 'eyJraWQiOiJBSURPUEsxIiwiYWxnIjoiUlMyNTYifQ.eyJpc3MiOiJodHRwczovL2FwcGxlaWQuYXBwbGUuY29tIiwiYXVkIjoiY29tLmFuYW5heWFyb3JhLmFwcGxlYXV0aGV4YW1wbGUiLCJleHAiOjE1NjY1MDIwMDIsImlhdCI6MTU2NjUwMTQwMiwic3ViIjoiMDAwMzEyLmZlNTNkMzhjYWMyNzQ5NjQ5YTMxMWJlNTZlYTQ5NWY3LjIzMzIiLCJjX2hhc2giOiJMMzEyNDRZRHl1Mk9BQ1ZNYlY0SE9BIiwiYXV0aF90aW1lIjoxNTY2NTAxNDAyfQ.lKE_kMSkw7Lg_3QqfjYO9uekSKRtUQfHK1oeu9erG9SIjc3Z7PpeyGBhcCjUOBFOxDGgdkL-xloWSs1Y8cH8_rga19ruOiuDiusnaHlTlkdwVvLtbA6Qp7dPUQszZRT9Cyh5Dk3l8WasosMSNEuHeGv_WI1JaKJuFJy3-QjGHSUzXH24uvvMAniL-YHlHwoNdWcWv14g7nup0BZNIUsrU-sR1IMhOy2Pc7h-tcgOPd8O_gitrP-18R3mtlRuSxAWuHqHCCzolvKSZLE9UalEN1Ep6blrLVOtMrib0Kjvy3NnkILMfr-ZhQoDkX3MddmKdFEcpoCRttWxau8Emxx8MQ' }
> ```

Did you un-authorize your account at Apple? The other properties are only submitted on your first login, so it should look like

```
{ state: '91626fe4d9',
  code: 'c0be...',
  id_token: 'eyJraWQiOiJBSURPUEsxI...',
  user: { firstName: 'Your Firstname', lastName: 'Your Lastname' }
```

… and the `email` being a property of the decoded id_token jWT.

**Comment by ananay** [comment]
@nicokaiser Awesome! The only thing I hadn't done was to unauthorize the app. It worked with my existing code. However, I'll still go ahead and merge your pull request. Thank you! :)

**Comment by ananay** [comment]
I'll also take care of the two points you stated above:

The state that is returned from Apple needs to be checked if it is the same that you sent (you might need to use sessions for this)

The client_secret (generated JWT) can have a much shorter TTL than 6 months. Maybe some minutes (as it is generated on every request anyway).

**Comment by arctouch-carlosbarreto** [comment]
Just a heads up for testing stuff, it is easier if we remove our Apple test account on appleid website and then create it again instead of un-authorize and authorize the Application again and again.

**Comment by araujobarret** [comment]
For testing stuff, it is easier if we remove our Apple test account on appleid website and then create again instead of un-authorizing and authorizing the Application again and again.

**Pull request merged**
